name: "Continuous Integration"

on:
  push:
    branches:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Format project files"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: node-server/.nvmrc
          cache: npm
          cache-dependency-path: node-server/package-lock.json
          working-directory: node-server

      - name: Install npm dependencies
        run: npm i
        working-directory: node-server

      - name: Check style with prettier
        run: npx prettier --check src/
        working-directory: node-server

      - name: Run unit tests
        run: npm test
        working-directory: node-server
